In [16]:
import torch

In [17]:
in_channels, out_channels = 5, 10
width, height = 100, 100
kernel_size = 3
batch_size = 1

# Create a random input tensor
input = torch.randn(batch_size, in_channels, width, height)

conv_layer = torch.nn.Conv2d(in_channels, out_channels, kernel_size)

output = conv_layer(input)

print(input.shape)
print(output.shape)
print(conv_layer.weight.shape)

torch.Size([1, 5, 100, 100])
torch.Size([1, 10, 98, 98])
torch.Size([10, 5, 3, 3])


In [19]:
input = [
    3, 4, 6, 5, 7,
    2, 4, 6, 8, 2,
    1, 6, 7, 8, 4,
    9, 7, 4, 6, 2,
    3, 7, 5, 4, 1
]
input = torch.tensor(input).reshape(1, 1, 5, 5).float()
print(input)

conv_layer = torch.nn.Conv2d(1, 1, 3, padding=1, bias=False)

kernel = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(1, 1, 3, 3).float()
print(kernel)

conv_layer.weight.data = kernel.data

output = conv_layer(input)
print(output)


tensor([[[[3., 4., 6., 5., 7.],
          [2., 4., 6., 8., 2.],
          [1., 6., 7., 8., 4.],
          [9., 7., 4., 6., 2.],
          [3., 7., 5., 4., 1.]]]])
tensor([[[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]])
tensor([[[[ 91., 168., 224., 215., 127.],
          [114., 211., 295., 262., 149.],
          [192., 259., 282., 214., 122.],
          [194., 251., 253., 169.,  86.],
          [ 96., 112., 110.,  68.,  31.]]]], grad_fn=<ConvolutionBackward0>)
