In [1]:
import torch

In [2]:
batch_size = 1
seq_len = 3
input_size = 4
hidden_size = 2

In [3]:
cell = torch.nn.RNNCell(input_size=input_size, hidden_size=hidden_size)

In [4]:
dataset = torch.randn(seq_len, batch_size, input_size)
print(dataset.shape)

torch.Size([3, 1, 4])


In [5]:
hidden = torch.zeros(batch_size, hidden_size)
print(hidden)

tensor([[0., 0.]])


In [6]:
for idx, input in enumerate(dataset):
  print('=' * 20, idx, '='*20)
  print('input size: ', input.shape)
  hidden = cell(input, hidden)

  print('outputs size:', hidden.shape)
  print(hidden)

==================== 0 ====================
input size:  torch.Size([1, 4])
outputs size: torch.Size([1, 2])
tensor([[0.8027, 0.5198]], grad_fn=<TanhBackward0>)
==================== 1 ====================
input size:  torch.Size([1, 4])
outputs size: torch.Size([1, 2])
tensor([[-0.3319, -0.8722]], grad_fn=<TanhBackward0>)
==================== 2 ====================
input size:  torch.Size([1, 4])
outputs size: torch.Size([1, 2])
tensor([[0.2885, 0.0455]], grad_fn=<TanhBackward0>)


In [7]:
batch_size = 1
seq_len = 3
input_size = 4
hidden_size = 2
num_layers = 1

In [8]:
cell = torch.nn.RNN(input_size=input_size, hidden_size=hidden_size, num_layers=num_layers)

In [9]:
inputs = torch.randn(seq_len, batch_size, input_size)
print('inputs', inputs)
hidden = torch.zeros(num_layers, batch_size, hidden_size)
print('hidden', hidden)

inputs tensor([[[ 0.7236,  1.3860, -0.1316, -0.0593]],

        [[-0.7949, -0.0634,  1.1094, -0.5888]],

        [[ 2.7299,  0.9197,  1.0787,  0.9876]]])
hidden tensor([[[0., 0.]]])


In [10]:
output, hidden = cell(inputs, hidden)

print('Output size: ', output.shape)
print('Output: ', output)

print('Hidden size: ', hidden.shape)
print('Hidden: ', hidden)

Output size:  torch.Size([3, 1, 2])
Output:  tensor([[[ 0.0468,  0.6008]],

        [[-0.2627, -0.3966]],

        [[-0.9603, -0.5755]]], grad_fn=<StackBackward0>)
Hidden size:  torch.Size([1, 1, 2])
Hidden:  tensor([[[-0.9603, -0.5755]]], grad_fn=<StackBackward0>)
